name: Quarantine validation

on:
  pull_request:
    branches:
      - main
      - v*-branch
    paths:
      - '**/scripts/quarantine*.yaml'
jobs:
  quarantine-info:
    runs-on: ubuntu-latest
    steps:
      - name: Add information about quarantine process
        run: |
          # Find existing comment
          comment_id=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments \
            --jq '.[] | select(.body | contains("Quarantine Process")) | .id' || echo "")
          
          if [ -n "$comment_id" ]; then
            # Comment exists - edit it
            gh pr comment "$PR_NUMBER" --body "$BODY" --edit-last
          else
            # No comment - create new one
            gh pr comment "$PR_NUMBER" --body "$BODY"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BODY: >
            Since quarantine was modified, please make sure
            you are following the process described in
            [quarantine process](https://nordicsemi.atlassian.net/wiki/spaces/NCS/pages/1104576817/Quarantine).
