name: Quarantine validation

on:
  pull_request_target:
    branches:
      - main
      - v*-branch
    paths:
      - '**/scripts/quarantine*.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  quarantine-info:
    runs-on: ubuntu-24.04
    steps:
      - name: Add information about quarantine process
        run: |
          # Find existing comment
          comment_id=$(gh pr view ${{ github.event.pull_request.number }} --json comments --jq '.comments[] | select(.body | contains("Quarantine Process")) | .id' || echo "")
          if [[ -z "$comment_id" ]]; then
            # No comment - create new one
            gh pr comment "$PR_NUMBER" --body "$BODY"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BODY: >
            Since quarantine was modified, please make sure
            you are following the process described in
            [Quarantine Process](https://nordicsemi.atlassian.net/wiki/spaces/NCS/pages/1104576817/Quarantine).
      - name: Get changed quarantined files
        run: |
          gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[] | select(.path | contains("scripts/quarantine")) | .path' > quarantined_files.txt
        id: quarantined_files
      - name: Add quarantined files to comment
        run: |
          echo "Changed quarantined files:" >> $COMMENT
          cat quarantined_files.txt >> $COMMENT
        env:
          COMMENT: ${{ steps.quarantine-info.outputs.comment }}